.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.TH CL-LAUNCH 1 "May 14th, 2012"
.SH NAME
CL-Launch \- Common Lisp program launcher and shell script generator
.SH DESCRIPTION
.B CL-Launch
provides a uniform way to invoke Common Lisp code from the shell
or to generate ecoxecutable shell scripts from Common Lisp source code,
independently from the underlying Common Lisp implementation.
.PP
Currently supported implementations are:
SBCL, Clozure CL, GNU CLISP, CMUCL, ECL, ABCL, XCL, SCL, Allegro, LispWorks Pro, GCL.
.PP
You can specify complex Lisp systems using ASDF 2.
cl-launch will leverage ASDF 2's per-user, per-implementation fasl cache.
It can dump precompiled images and resume from them, for fast software startup.
It also integrates well with XCVB.
.PP
cl-launch contains its own complete documentation.
You can view it all using the following command:
.PP
.RS
.nf
\fBcl-launch \-\-more-help | less\fP
.fi
.RE
.PP
